### PR TITLE
Delay init

### PR DESCRIPTION
**Pull request by dobromir-hristov**
## What does it do?

It adds a prop to stop init on `mounted` and allows the user to init when they decide.

Adds small secondary fixes to so ESLint is green

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
@alvarotrigo should this go into `dev` or `master`?

**Comment by ChromaticMind** [comment]
@alvarotrigo please can this be merged in soon? This resolves https://github.com/alvarotrigo/vue-fullpage.js/issues/138

**Comment by alvarotrigo** [comment]
> @alvarotrigo should this go into `dev` or `master`?

Dev :)

**Comment by alvarotrigo** [comment]
Thanks for that @dobromir-hristov !! ;)
We probably need to add something to do docs regarding how to use it. Want to do the PR too? If not, I assume this is the way of using it?

```js
export default {
    name: 'app',
    data () {
      return {
        delayInit: true,
        options: {
          licenseKey: 'YOUR_KEY_HERE',
         }
    },
   methods: {
   }
}
```

**Comment by dobromir-hristov** [comment]
Oh damn the docs.... asap

**Comment by alvarotrigo** [comment]
Awesome! Thanks for that again! 👏 👏 👏

**Comment by dobromir-hristov** [comment]
I have not built it though. I wasnt expecting to have such a large diff, I guess dev was behind Master...

**Comment by alvarotrigo** [comment]
> I guess dev was behind Master...

It wasn't. Not quite sure why it showed all those changes.

**Comment by dobromir-hristov** [comment]
Because I forked Master :)

**Comment by dobromir-hristov** [comment]
Ah no ... ESLint :D

**Comment by ChromaticMind** [comment]
just to check guys, for Vue Nuxt, should I say `delayInit: true,` in the options object?

**Comment by alvarotrigo** [comment]
Updated dist files!


> just to check guys, for Vue Nuxt, should I say `delayInit: true,` in the options object?

Now he changed it to "skipInit"

**Comment by alvarotrigo** [comment]
@ChromaticMind you can read the docs here:
https://github.com/alvarotrigo/vue-fullpage.js/tree/dev#delayed-init

**Comment by alvarotrigo** [comment]
And you can use the dev branch by doing:

```sh
npm install alvarotrigo/vue-fullpage.js#dev
```

**Comment by ChromaticMind** [comment]
thank you both @dobromir-hristov and @alvarotrigo , I am going to test this out now!

**Comment by ulisses-cruz** [comment]
Thanks! I'll have a look on it.

**Pull request merged**
