### PR TITLE
docs: add nuxt.js usage examples

### LINKED ISSUE #73: Improve docs regarding Nuxt.js compatibility
Regarding the conversation in the issue https://github.com/alvarotrigo/vue-fullpage.js/issues/6, we need a way to clarify how to use the vue wrapper when using it together with Nuxt.js.

Any help will be appreciated!

### PR DESCRIPTION
**Pull request by dobromir-hristov**
Describes how to use vue-fullpage.js with nuxt
FIXES #73

### CODE REVIEW

**Comment by alvarotrigo** [comment]
@dobromir-hristov awesome! Thanks a lot for that!

Could you please change the branch you commited it from `master` to `dev` as detailed in the [contributing docs](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/CONTRIBUTING.md)? I always commit to dev and only use master to merge the changes once I publish a new release.

**Comment by dobromir-hristov** [comment]
@alvarotrigo should be fine now?

**Comment by alvarotrigo** [comment]
Awesome! Thanks! 
Merged!

**Comment by dobromir-hristov** [comment]
Yes! 😆

**Comment by alvarotrigo** [comment]
I've merged it in the new release 0.1.0.
You can now see yourself as a contributor here:
https://github.com/alvarotrigo/vue-fullpage.js/graphs/contributors

Congrats! :)

**Pull request merged**
