### PR TITLE
docs: add nuxt.js setup instructions using plugin

### PR DESCRIPTION
**Pull request by vaso2**
Describes how to integrate vue-fullpage.js with nuxt in one line in config

### CODE REVIEW

**Comment by vaso2** [comment]
Hi! Any movements on this?

**Comment by alvarotrigo** [comment]
Thanks for the reminder!
Looking good to me!

Would it be possible to change the nuxt-fullpage.js license from MIT to GPLv3?
It might lead to confusion having a MIT licensed software which uses a GPLv3 dependency, as they are not compatible with each other :)

**Comment by vaso2** [comment]
Sure! I'm living in a country, where everyone knows nothing or cares nothing about licencing:)

**Comment by alvarotrigo** [comment]
😆 haha ok. 
Please let me know when you change it and publish a new release with the change.

**Comment by vaso2** [comment]
Done. Also, you forgot MIT in your own package.json:)

**Comment by alvarotrigo** [comment]
@vaso2 true! I've just changed it!

**Comment by alvarotrigo** [comment]
Merged! Thanks for it!

**Pull request merged**
