### PR TITLE
Import Fix

### PR DESCRIPTION
**Pull request by Gene-Dana**
Gotta use these curly brackets for it to work.

### CODE REVIEW

**Comment by Gene-Dana** [comment]
this is my second merge! bear with my noobness

**Comment by alvarotrigo** [comment]
The provided [webpack demo](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/webpack/src/main.js#L9) works as expected without those?

**Comment by Gene-Dana** [comment]
No it did not work without those!

**Comment by alvarotrigo** [comment]
Works for me!
Here's the prove in Codesandbox:
https://codesandbox.io/s/xl1n7kxv4w

You'll have to provide an isolated reproduction in codesandbox if you believe this is some kind of issue.
So far I'll close the issue until proven there's really a bug.

**Pull request closed without merging**
